[package]
name = "BlueGauge"
version = "0.3.7"
edition = "2024"
description = "A lightweight tray tool for easy viewing of the battery level of the Bluetooth device."
authors = ["iKineticate <https://github.com/iKineticate>"]
repository = "https://github.com/iKineticate/BlueGauge"
license = "MIT"

[dependencies]
anyhow = "1.0.102"

env_logger = { version = "0.11.10", default-features = false, features = ["auto-color", "humantime"] }
log = { version = "0.4.29", features = ["release_max_level_off"] }

image = { version = "0.25.10", default-features = false, features = ["ico", "png"] }
ab_glyph = { version = "0.2.32", default-features = false, features = ["std"] }  # 字体渲染
piet-common = "0.8.0" # 图标渲染

serde= { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"

getset = "0.1.6" # 结构体库：方便设置和获取字段方法
strum = { version = "0.28.0", features = ["derive"] } # 枚举库：转字符、迭代器

tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread", "sync", "time"] }
futures = "0.3.32"

tray-icon = "0.23.1"
tauri-winrt-notification = "0.7.2"

dashmap = "=7.0.0-rc2"
scopeguard = "1.2.0"
windows_pnp = { path = "libs/windows_pnp" }
winit = "0.30.13"
winreg = "0.56.0"

[dependencies.windows]
version = "0.62.2"
features = [
    "Devices_Bluetooth",
    "Devices_Bluetooth_GenericAttributeProfile",
    "Devices_Enumeration",
    "Foundation_Collections",
    "Storage_Streams",
    "Win32_Globalization",
    "Win32_Graphics_DirectWrite",
    "Win32_Security",
    "Win32_System",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_UI_Controls",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]

[dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32_Devices_Properties",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Wdk_Devices_Bluetooth",
]

[dev-dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Devices_Bluetooth",
    "Devices_Bluetooth_Rfcomm",
    "Networking_Sockets",
    "Win32_Devices_Properties"
]

[build-dependencies]
embed-resource = "3.0.9"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = true